### ISSUE TITLE
start errors.....when used "ssl": true

### ISSUE THREAD

**Issue by plutosherry** [danielperna84/hass-configurator#106]
INFO:2018-08-06 16:36:57,021:__main__:Starting server
Traceback (most recent call last):
  File "/configurator.py", line 4841, in <module>
    main(sys.argv[1:])
  File "/configurator.py", line 4831, in main
    server_side=True)
  File "/usr/local/lib/python3.6/ssl.py", line 1149, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python3.6/ssl.py", line 747, in __init__
    self._context.load_cert_chain(certfile, keyfile)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by danielperna84** [comment]
This is a known issue. It has been solved in the thread in the forum:https://community.home-assistant.io/t/configurator-stopped-working-after-update-to-1-0/62582
Basically all you have to do is to prepend your certificate and key with `/ssl/` to make it `/ssl/fullchain.pem`.
