### ISSUE TITLE
VERIFY_HOSTNAME returning error

### ISSUE THREAD

**Issue by perimore** [danielperna84/hass-configurator#134]
Suddenly getting this error below since upgrading HA to 0.83.3.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./configurator.py", line 4719, in do_GET
    if not verify_hostname(self.headers.get('Host', '')):
  File "./configurator.py", line 3688, in verify_hostname
    if VERIFY_HOSTNAME not in request_hostname:
TypeError: 'in <string>' requires string as left operand, not bool
```

My config looks correct:

...
    "VERIFY_HOSTNAME": true,
...

I tried changing to a string, i.e. "true" but then got forbidden as this was returning false leading to a 404.

3685 in configurator.py
```
def verify_hostname(request_hostname):
    """Verify the provided host header is correct."""
    if VERIFY_HOSTNAME:
        if VERIFY_HOSTNAME not in request_hostname:
            return False
    return True
```

**Comment by danielperna84** [comment]
Have a look at the documentation for that option: https://github.com/danielperna84/hass-configurator#verify_hostname-string
It should be your hostname, not some bool-variation. To verify the hostname the configurator needs to know what the hostname is. I wonder how it could have worked before your upgrade (although Home Assistant updates are 99% irrelevant for the configurator).

**Comment by perimore** [comment]
My bad, thanks!
