### ISSUE TITLE
Hue state error using HA bridge

### ISSUE THREAD

**Issue by jamesshoemaker** [danielperna84/hass-configurator#57]
keeps spewing this out

2017-10-31 12:34:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for light.tiffany_table fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 309, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/light/hue.py", line 467, in update
    self.update_lights(no_throttle=True)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/light/hue.py", line 239, in update_lights
    lights[light_id].schedule_update_ha_state()
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 278, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'

**Comment by danielperna84** [comment]
That's not an issue related to the configurator. https://github.com/home-assistant/home-assistant/issues would be the right place for this.
